steps:
  - name: 'gcr.io/cloud-builders/gradle'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y openjdk-22-jdk && \
        update-java-alternatives -s java-1.22.0-openjdk-amd64 && \
        export JAVA_HOME=/usr/lib/jvm/java-22-openjdk-amd64 && \
        export PATH=$JAVA_HOME/bin:$PATH && \
        gradle clean bootJar
    id: 'Build JAR'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-boot-app', '.']
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-boot-app']
    id: 'Push Docker Image'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'spring-boot-app', '--image', 'gcr.io/$PROJECT_ID/spring-boot-app', '--platform', 'managed', '--region', 'us-central1']
    id: 'Deploy to Cloud Run'

images:
  - 'gcr.io/$PROJECT_ID/spring-boot-app'
options:
  logging: CLOUD_LOGGING_ONLY
