steps:
  - name: 'openjdk:21-jdk-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget unzip
        wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
        unzip gradle-7.5-bin.zip -d /opt
        ln -s /opt/gradle-7.5/bin/gradle /usr/bin/gradle
        chmod +x /usr/bin/gradle
        gradle -v
        chmod +x gradlew
        ./gradlew build --no-daemon

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hookapp-be'  # Updated image tag to use 'hook-app-be'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hookapp-be'  # Updated image tag to use 'hook-app-be'
    id: 'Push Docker Image'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hook-app-be'  # Updated service name to 'hook-app-be'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hookapp-be'  # Updated image tag to use 'hook-app-be'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west3'
    id: 'Deploy to Cloud Run'

images:
  - 'gcr.io/$PROJECT_ID/hookapp-be'  # Updated image tag to use 'hook-app-be'
options:
  logging: CLOUD_LOGGING_ONLY
