steps:
  - name: 'ubuntu'
    args: ['bash', '-c', 'apt-get update && apt-get install -y openjdk-21-jdk && update-java-alternatives -s java-1.21.0-openjdk-amd64']
    id: 'Setup JDK 21'

  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'bootJar']
    id: 'Build JAR'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-boot-app', '.']
    id: 'Build Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring
